name: docker-push

on:
    workflow_dispatch:
    push:
      branches:
        - 'Upgrade_To_Interfaces_And_Services'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: "{{defaultContext}}:MultiThreadFileAccess"
            push: true
            tags: sajin08/multithreadfileaccess:latest
